# Generated by Django 5.2.7 on 2025-12-26 16:25

import authentication.services.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='media/default/default.jpg', upload_to=authentication.services.upload_path.user_profile_pic_path),
        ),
    ]
